### ISSUE TITLE
notifyURL 这个参数有效么？

### ISSUE THREAD

**Issue by cobola** [SunGg12138/node-qiniu-sdk#8]
```
result = await NodeQiniuSDK.av.hls({
    pfop: nqs.pfop({
      bucketName: qnFM.bucket,
      fileName: qnFM.filename
    }),
    saveas: {
      bucketName: qnFM.bucket,
      fileName: qnFM.filename + '.m3u8'
    },
    noDomain: '1',
    segtime: 10,
    isForce: true,
    pattern: qnFM.filename + '-$(count)',
    notifyURL: 'https://xxxx.com/qn/notify'
  })

```

转换成功后 并没有收到notify  我看了下源码 似乎也没有什么问题 
这样用对么？

**Comment by cobola** [comment]
果然是写错了

result = await NodeQiniuSDK.av.hls({
    pfop: nqs.pfop({
      bucketName: qnFM.bucket,
      fileName: qnFM.filename,
    notifyURL: 'https://xxxx.com/qn/notify'
    }),
    saveas: {
      bucketName: qnFM.bucket,
      fileName: qnFM.filename + '.m3u8'
    },
    noDomain: '1',
    segtime: 10,
    isForce: true,
    pattern: qnFM.filename + '-$(count)',
  })

应该这样

**Comment by SunGg12138** [comment]
我刚看到，就被你close了
