### ISSUE TITLE
上传文件 可以用base64 或者 data 直接上传么？

### ISSUE THREAD

**Issue by cobola** [SunGg12138/node-qiniu-sdk#9]
比如小程序里面穿一个图片
用路径的话 比如直接传方便

**Comment by SunGg12138** [comment]
是可以直接上传的：

> // 上传文件的时候，指定encoding为base64就可以了
> .upload({ encoding: 'base64', txt: '<图片base64>' })

**Comment by cobola** [comment]
gooood
